const ActionConstant = {
    AUTHENTICATE_USER : 'AUTHENTICATE_USER',
    AUTHENTICATE_USER_SUCCESS : 'AUTHENTICATE_USER_SUCCESS',
    AUTHENTICATE_USER_FAILURE : 'AUTHENTICATE_USER_FAILURE',
    FETCH_USER_REWARDS: 'FETCH_USER_REWARDS',
    FETCH_USER_REWARDS_SUCCESS: 'FETCH_USER_REWARDS_SUCCESS',
    FETCH_USER_REWARDS_FAILURE: 'FETCH_USER_REWARDS_FAILURE',
    FETCH_USER_TRANSACTIONS : 'FETCH_TRANSACTIONS_BEGIN',
    FETCH_USER_TRANSACTIONS_SUCCESS : 'FETCH_TRANSACTIONS_SUCCESS',
    FETCH_USER_TRANSACTIONS_FAILURE : 'FETCH_TRANSACTIONS_FAILURE',
    UPDATE_ACTIVE_MONTH: 'UPDATE_ACTIVE_MONTH'
}
export default ActionConstant;